import Head from "next/head";
import Image from "next/image";

import Header from "@components/Header";
import Container from "@components/Container";

import styles from "@styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Container>
          <h1>Strange Wilderness Granola</h1>
          <h2>Available Flavors</h2>
          <ul>
            <li>
              <img src="/images/vanilla-cranberry-granola.jpg" alt="Vanilla Cranberry Granola"/>
              <h3>Vanilla Cranberry Granola</h3>
              <p>$7.99</p>
              <p>
                <button>Add to Cart</button>
              </p>
            </li>
            <li>
              <img src="/images/vanilla-cranberry-granola.jpg" alt="Vanilla Cranberry Granola"/>
              <h3>Vanilla Cranberry Granola</h3>
              <p>$7.99</p>
              <p>
                <button>Add to Cart</button>
              </p>
            </li>
            <li>
              <img src="/images/vanilla-cranberry-granola.jpg" alt="Vanilla Cranberry Granola"/>
              <h3>Vanilla Cranberry Granola</h3>
              <p>$7.99</p>
              <p>
                <button>Add to Cart</button>
              </p>
            </li>
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        Strange Wilderness Granola {new Date().getFullYear()}
      </footer>
    </div>
  );
}
